<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Packet Label</title>
</head>
<body>

<div class="header">
    <h1>Packet Label</h1>
</div>

<div class="details">
    <p>Date: {{ $packet->date }}</p>
    <p>ID: {{ $packet->tracking_number }}</p>
    <p>Format: {{ $packet->format }}</p>
    <p>Weight: {{ $packet->weight }}</p>
</div>

<div class="shipping-details">
    <h2>Shipping address</h2>
    <p>{{ $packet->shipping_street }} {{ $packet->shipping_house_number }}</p>
    <p>{{ $packet->shipping_zip_code }} {{ $packet->shipping_city }}</p>
</div>

<div class="delivery-details">
    <h2>Delivery address</h2>
    <p>{{ $packet->delivery_street }} {{ $packet->delivery_house_number }}</p>
    <p>{{ $packet->delivery_zip_code }} {{ $packet->delivery_city }}</p>
</div>

<br>
<div class="footer">
    <p>Generated by TrackR</p>
</div>
</body>
</html>
